### ISSUE TITLE
P0 - Change Logic For When To Turn Off/On Lidar At 2nd/3rd Waypoint

### ISSUE THREAD

**Issue by 1999michael** [UTRA-ART/Caffeine#104]
**Description:**
- We want to change the logic in nav/filter_lidar_data/src/ignore_lidar_node.cpp to determine when we are at the 2nd/3rd waypoint. Aim to publish a topic (likely some int) from nav/load_waypoints/scripts/navigate_waypoints.py to say which waypoint we are aiming for, and subscribe to that topic in ignore_lidar_node.cpp

**Goals:**
- [ ] (navigate_waypoints.py changes) Add topic to publish which waypoint number we are aiming for
- [ ] (ignore_lidar_node.cpp changes) Add subscriber to figure out what waypoint we are aiming for, and turn on/off lidar accordingly
- [ ] Remove hard coded values & bounds logic from ignore_lidar_node.cpp

**Acceptance Criteria:**
- [ ] Turns on/off lidar only when move_base/load_waypoints sets a new waypoint (can see what move_base is aiming for in rviz)

**Notes:**
- Any message type that at least publishes a single number is probably sufficient
- Although we can extend the bounds, having the logic to define when we are at the 2nd/3rd waypoint in only 1 place is better

**Comment by Raindancer0912** [comment]
No longer using strategy of turning lidar on/off
