### ISSUE TITLE
P3 - Connect RTAB Map

### ISSUE THREAD

**Issue by erickmu1** [UTRA-ART/Caffeine#12]
**Description:**
- RTAB Map performs SLAM and thus creates a map of the robot's surroundings
- We will need such a map, hence we connect it to the Navigation Stack

**Goals:**
- [ ] Connect appropriate topics to RTAB Map
- [ ] Run RTAB Map
- [ ] Connect RTAB Map to the Navigation Stack

**Acceptance Criteria:**
- [ ] Produced Point Clouds and Occupancy Grids should match the environment the robot sees
- [ ] Caffeine navigates at least as well as when the Navigation Stack was only used
- [ ] Can send nav goals to any location in the simulated world (within reason)

**Notes:**
- We use RTAB Map over a SLAM package such as gmapping because it supports camera inputs and allows for mutliple configurations
- Goal is not to finely tune RTAB Map, but to get it working well enough
- Camera should be tilted at an angle 
- Documentation: http://wiki.ros.org/rtabmap_ros
- Old implementation: https://github.com/UTRA-ART/SLAM-1920/tree/dev/slam-ws/src/nav_rtab

**Comment by Raindancer0912** [comment]
Currently implementing another SLAM package: Cartographer. May reopen a later time
