### ISSUE TITLE
P3 - Load and Localize Against a Static Map

### ISSUE THREAD

**Issue by erickmu1** [UTRA-ART/Caffeine#13]
**Description:**
- Potentially we can map the IGVC course before hand. So we need to be able to map, store, load, and localize against the environment

**Goals:**
- [ ] Save static map
- [ ] Load static map
- [ ] Localize against static map
- [ ] Navigate with loaded static map (+ augment/correct the map)

**Acceptance Criteria:**
- [ ] The above goals are met and autonomous navigation works at least as well as before we used a static map
- [ ] Wiki explaining the pipeline to get all this done

**Notes:**
- RTAB Map provides all this functionality, just figure out how to use it.

**Comment by Raindancer0912** [comment]
Currently irrelevant. May reopen at later date
