### ISSUE TITLE
P2 - Update Occupancy Grid with CV Obstacles

### ISSUE THREAD

**Issue by erickmu1** [UTRA-ART/Caffeine#20]
**Description:**
- Given obstacles that can only be detected using CV, we need to update the occupancy grid so that Caffeine can recognize those obstacles

**Goals:**
- [ ] Determine obstacle pose with respect to the `map` frame
- [ ] Update the occupancy with this obstacle

**Acceptance Criteria:**
- [ ] CV obstacles are visible on the occupancy grid
- [ ] Caffeine avoids CV obstacles when navigating autonomously

**Notes:**
- If you need more information about the obstacles determined by the @UTRA-ART/computer-vision-and-machine-learning team, ask them

**Comment by Raindancer0912** [comment]
Using alternative strategy for adding lane and pothole detection to the occupancy grid
