### ISSUE TITLE
Connect PointClouds to the Navigation Stack

### ISSUE THREAD

**Issue by erickmu1** [UTRA-ART/Caffeine#47]
**Description:**
- This issue should follow after #46 
- At this point, we should be able to un-comment the point_cloud observation source and use it for the navigation stack
- Moreover we should no longer need the hotfix of limiting the laser_scan by range, but rather by heigh

**Goals:**
- [x] Connect point cloud to the nav_stack
- [ ] remove obstacle_range configuration and use an appropriate min_obstacle_height instead

**Acceptance Criteria:**
- [x] Costmap is populated by both the Lidar and Stereo cam
- [ ] Can navigate autonomously with Lidar, Stereo cam, or both

**Notes:**
- Re-open #46 if there are persistent tilt issues

**Comment by drinkerciku** [comment]
'min_obstacle_height' needs to be specified under the instance of each observation source in costmap_common_params.yaml file. the min_obstacle_height defaults to 0 in the master branch.

'max_obstacle_height' can be defined globally and overwritten locally (under specific observation sources instances) if needed.

**Comment by drinkerciku** [comment]
obstacle_range cannot be removed as obstacles will not be registered at all --> empty costmap

**Comment by drinkerciku** [comment]
The 'min_obstacle_height' works with reference to the visual odometry and if it is loss readings become inconsistent --> hard to navigate with the camera only. I also left some comments on Michael's issue in terms of visual odometry loss.
