### ISSUE TITLE
Cleaning the repository 

### ISSUE THREAD

**Issue by kajananchinniah** [UTRA-ART/Caffeine#54]
**Description:**
- This is an ongoing issue to clean up the repository.

**Goals:**
- [x] Ensure all code is readable and understandable.
- [ ] Update documentation.

**Acceptance Criteria:**
- [x] The robot should have the same functionality as prior to cleaning. 
- [x] Reviewers should be happy with the code 

**Notes:**
- https://wiki.ros.org/DevelopersGuide.

**Comment by 1999michael** [comment]
- [ ] odom/odom -> odom
- [ ] nav_goal -> load_waypoints
- [ ] Remove robot folder
- [ ] battery should go into chassis
- [ ] Remove caffeine prefix/namespace (HARD)
- [ ] Move all TO DO to somewhere in GitHub
- [ ] Move robot joints to includes
- [ ] Remove laser file
