### ISSUE TITLE
P2 - Add obstacles onto the local costmap 

### ISSUE THREAD

**Issue by kajananchinniah** [UTRA-ART/Caffeine#57]
**Description:**
- Given a coordinate array representing the location of obstacles, you should those obstacles onto the local costmap.

**Goals:**
- [x] See obstacles on top of local costmap 

**Acceptance Criteria:**
- [x] Does not affect global costmap 
- [x] Does not overwrite the current local costmap
- [x] Successfully adds the obstacles to the costmap 
- [x] Linearly connect coordinate points together 

**Notes:**
- Provide any additional notes/resources that might be helpful in the completion of this task.

**Comment by kajananchinniah** [comment]
Update:
- Need to ensure that config files are up to date with master 
- Need to ensure that camera is only in global costmap and LIDAR is only in local costmap 
- Need a way to clear the obstacles after either every update or periodically (periodically is probably better)
- Need a method to linearly connect coordinate points together (see: https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm). Note, must ensure that we don't linearly connect points that are on different sides.

**Comment by 1999michael** [comment]
(seems to be useful)
https://answers.ros.org/question/348776/specifying-plugins-to-local_costmapyaml-causes-it-to-disappear/

**Comment by 1999michael** [comment]
Action Items (addition to kj's apr update)
 - Understand grid_layer vs. simple_layers cpp code does (http://wiki.ros.org/costmap_2d/Tutorials/Creating%20a%20New%20Layer)
 - (I think we should use grid_layers for saving history? need to be sure)
 - Interface with CV code (later). For now, use dummy array, that changes
    - From surface level looks, seems that we need to subscribe to a dummy topic and use callback function to process it

**Comment by 1999michael** [comment]
- Simple Layers: History is not kept
- Grid Layers: History is kept

**Comment by 1999michael** [comment]
Parent Class Documentation (look around for other inheritance classes)
- http://docs.ros.org/en/jade/api/costmap_2d/html/classcostmap__2d_1_1Layer.html

**Comment by 1999michael** [comment]
Main goal is to understand updateBounds and updateCosts functions, when they get called, and what they do

**Comment by 1999michael** [comment]
For testing reasons, we aim to work on global costmap, and see if we can build upon the old walls we added ourselves. 

This assume CV data is "stable" (changes can be made if assumption is wrong)
