### ISSUE TITLE
P0 - Update worlds

### ISSUE THREAD

**Issue by kajananchinniah** [UTRA-ART/Caffeine#65]
**Description:**
- Need to update the world to accurately depict 2022 test environment

**Acceptance Criteria (Base World):**
- [ ] The ramps should have lanes on the edges of the ramp (15 degree incline, green color)
- [x] The ramp should be where the new location is
- [x] The barrels should be at each of the dots
- [x] The floor should look like the 2022 rules' parking lot map (lanes, grey floor, yellow lines)
- [x] Some walls for the barricade

**Other World Variants:**
- [x] A world without the ramp
- [x] A world with walls on top of the white lines (with ramps)
- [x] A world with walls on top of the white lines (without ramps)

**Notes:**
- We should make a copy of the old worlds, and place in an a diff folder
- http://www.igvc.org/2022rules.pdf, page 7 for a map of the world

**Comment by 1999michael** [comment]
white circles -> simulated potholes (do nothing)
other circles -> construction barrels of the appropriate color
Additional future work -> Random lamp posts / street signs?
