### ISSUE TITLE
P0 - Use Kinect instead of ZED in simulation

### ISSUE THREAD

**Issue by kajananchinniah** [UTRA-ART/Caffeine#79]
**Description:**
- Update camera to use Kinect since we plan on switching camera

**Goals:**
- [ ] Add Kinect camera with the same functionality as zed
- [ ] Update topics to use the new kinect
- [ ] Remove unused topics & unused packages

**Acceptance Criteria:**
- [ ] Relevant topics are published and updated to be used
- [ ] Kinect works the same as zed

**Notes:**
- There seems to be a kinect plugin so we should try leveraging it
- We need to figure out relevant info about the camera (I haven't been able to find a datasheet).

**Comment by Raindancer0912** [comment]
Closed because Kinect doesn't work well outdoors
